package com.devlost.jinvest.model;
// Generated 18/10/2017 19:15:54 by Hibernate Tools 4.3.1



/**
 * Category generated by hbm2java
 */
public class Category  implements java.io.Serializable {


     private long categoryId;
     private String description;
     private String name;

    public Category() {
    }

	
    public Category(long categoryId, String name) {
        this.categoryId = categoryId;
        this.name = name;
    }
    public Category(long categoryId, String description, String name) {
       this.categoryId = categoryId;
       this.description = description;
       this.name = name;
    }
   
    public long getCategoryId() {
        return this.categoryId;
    }
    
    public void setCategoryId(long categoryId) {
        this.categoryId = categoryId;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }




}


