package com.devlost.jinvest.model;
// Generated 18/10/2017 19:15:54 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Fund generated by hbm2java
 */
public class Fund  implements java.io.Serializable {


     private long id;
     private Category category;
     private Risk risk;
     private BigDecimal additionalPurchase;
     private String fundName;
     private Integer holdPeriod;
     private BigDecimal managementFee;
     private BigDecimal minimumBalance;
     private BigDecimal minimumInvestment;
     private BigDecimal minimumRedeem;
     private Long performanceFee;
     private Long purchaseFee;
     private Integer redeemPeriod;
     private Integer settlePeriod;
     private BigDecimal sharePrice;
     private Date startDate;
     private BigDecimal totalNetAsset;
     private Long withdrawFee;
     private Boolean locked;
     private Set<Transaction> transactions = new HashSet<Transaction>(0);
     private Set<UsersFunds> usersFundses = new HashSet<UsersFunds>(0);

    public Fund() {
    }

	
    public Fund(long id, String fundName) {
        this.id = id;
        this.fundName = fundName;
    }
    public Fund(long id, Category category, Risk risk, BigDecimal additionalPurchase, String fundName, Integer holdPeriod, BigDecimal managementFee, BigDecimal minimumBalance, BigDecimal minimumInvestment, BigDecimal minimumRedeem, Long performanceFee, Long purchaseFee, Integer redeemPeriod, Integer settlePeriod, BigDecimal sharePrice, Date startDate, BigDecimal totalNetAsset, Long withdrawFee, Boolean locked, Set<Transaction> transactions, Set<UsersFunds> usersFundses) {
       this.id = id;
       this.category = category;
       this.risk = risk;
       this.additionalPurchase = additionalPurchase;
       this.fundName = fundName;
       this.holdPeriod = holdPeriod;
       this.managementFee = managementFee;
       this.minimumBalance = minimumBalance;
       this.minimumInvestment = minimumInvestment;
       this.minimumRedeem = minimumRedeem;
       this.performanceFee = performanceFee;
       this.purchaseFee = purchaseFee;
       this.redeemPeriod = redeemPeriod;
       this.settlePeriod = settlePeriod;
       this.sharePrice = sharePrice;
       this.startDate = startDate;
       this.totalNetAsset = totalNetAsset;
       this.withdrawFee = withdrawFee;
       this.locked = locked;
       this.transactions = transactions;
       this.usersFundses = usersFundses;
    }
   
    public long getId() {
        return this.id;
    }
    
    public void setId(long id) {
        this.id = id;
    }
    public Category getCategory() {
        return this.category;
    }
    
    public void setCategory(Category category) {
        this.category = category;
    }
    public Risk getRisk() {
        return this.risk;
    }
    
    public void setRisk(Risk risk) {
        this.risk = risk;
    }
    public BigDecimal getAdditionalPurchase() {
        return this.additionalPurchase;
    }
    
    public void setAdditionalPurchase(BigDecimal additionalPurchase) {
        this.additionalPurchase = additionalPurchase;
    }
    public String getFundName() {
        return this.fundName;
    }
    
    public void setFundName(String fundName) {
        this.fundName = fundName;
    }
    public Integer getHoldPeriod() {
        return this.holdPeriod;
    }
    
    public void setHoldPeriod(Integer holdPeriod) {
        this.holdPeriod = holdPeriod;
    }
    public BigDecimal getManagementFee() {
        return this.managementFee;
    }
    
    public void setManagementFee(BigDecimal managementFee) {
        this.managementFee = managementFee;
    }
    public BigDecimal getMinimumBalance() {
        return this.minimumBalance;
    }
    
    public void setMinimumBalance(BigDecimal minimumBalance) {
        this.minimumBalance = minimumBalance;
    }
    public BigDecimal getMinimumInvestment() {
        return this.minimumInvestment;
    }
    
    public void setMinimumInvestment(BigDecimal minimumInvestment) {
        this.minimumInvestment = minimumInvestment;
    }
    public BigDecimal getMinimumRedeem() {
        return this.minimumRedeem;
    }
    
    public void setMinimumRedeem(BigDecimal minimumRedeem) {
        this.minimumRedeem = minimumRedeem;
    }
    public Long getPerformanceFee() {
        return this.performanceFee;
    }
    
    public void setPerformanceFee(Long performanceFee) {
        this.performanceFee = performanceFee;
    }
    public Long getPurchaseFee() {
        return this.purchaseFee;
    }
    
    public void setPurchaseFee(Long purchaseFee) {
        this.purchaseFee = purchaseFee;
    }
    public Integer getRedeemPeriod() {
        return this.redeemPeriod;
    }
    
    public void setRedeemPeriod(Integer redeemPeriod) {
        this.redeemPeriod = redeemPeriod;
    }
    public Integer getSettlePeriod() {
        return this.settlePeriod;
    }
    
    public void setSettlePeriod(Integer settlePeriod) {
        this.settlePeriod = settlePeriod;
    }
    public BigDecimal getSharePrice() {
        return this.sharePrice;
    }
    
    public void setSharePrice(BigDecimal sharePrice) {
        this.sharePrice = sharePrice;
    }
    public Date getStartDate() {
        return this.startDate;
    }
    
    public void setStartDate(Date startDate) {
        this.startDate = startDate;
    }
    public BigDecimal getTotalNetAsset() {
        return this.totalNetAsset;
    }
    
    public void setTotalNetAsset(BigDecimal totalNetAsset) {
        this.totalNetAsset = totalNetAsset;
    }
    public Long getWithdrawFee() {
        return this.withdrawFee;
    }
    
    public void setWithdrawFee(Long withdrawFee) {
        this.withdrawFee = withdrawFee;
    }
    public Boolean getLocked() {
        return this.locked;
    }
    
    public void setLocked(Boolean locked) {
        this.locked = locked;
    }
    public Set<Transaction> getTransactions() {
        return this.transactions;
    }
    
    public void setTransactions(Set<Transaction> transactions) {
        this.transactions = transactions;
    }
    public Set<UsersFunds> getUsersFundses() {
        return this.usersFundses;
    }
    
    public void setUsersFundses(Set<UsersFunds> usersFundses) {
        this.usersFundses = usersFundses;
    }




}


