package com.devlost.jinvest.model;
// Generated 18/10/2017 19:15:54 by Hibernate Tools 4.3.1



/**
 * Risk generated by hbm2java
 */
public class Risk  implements java.io.Serializable {


     private long riskId;
     private String description;
     private String name;

    public Risk() {
    }

	
    public Risk(long riskId, String name) {
        this.riskId = riskId;
        this.name = name;
    }
    public Risk(long riskId, String description, String name) {
       this.riskId = riskId;
       this.description = description;
       this.name = name;
    }
   
    public long getRiskId() {
        return this.riskId;
    }
    
    public void setRiskId(long riskId) {
        this.riskId = riskId;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }




}


