package com.devlost.jinvest.model;
// Generated 18/10/2017 19:15:54 by Hibernate Tools 4.3.1

import java.math.BigDecimal;
import java.util.Date;

/**
 * Transaction generated by hbm2java
 */
public class Transaction implements java.io.Serializable {

    private Long transactionId;
    private Fund fund;
    private UserProfile userProfile;
    private BigDecimal ammount;
    private Date submitDate;
    private Date settlementDate;
    private Byte completed;
    private String type;

    public static enum Type {
        BUY, SELL
    }

    public Transaction() {
    }

    public Transaction(Fund fund, UserProfile userProfile, BigDecimal ammount, Date submitDate, String type) {
        this.fund = fund;
        this.userProfile = userProfile;
        this.ammount = ammount;
        this.submitDate = submitDate;
        this.type = type;
    }

    public Transaction(Fund fund, UserProfile userProfile, BigDecimal ammount, Date submitDate, Date settlementDate, Byte completed, String type) {
        this.fund = fund;
        this.userProfile = userProfile;
        this.ammount = ammount;
        this.submitDate = submitDate;
        this.settlementDate = settlementDate;
        this.completed = completed;
        this.type = type;
    }

    public Long getTransactionId() {
        return this.transactionId;
    }

    public void setTransactionId(Long transactionId) {
        this.transactionId = transactionId;
    }

    public Fund getFund() {
        return this.fund;
    }

    public void setFund(Fund fund) {
        this.fund = fund;
    }

    public UserProfile getUserProfile() {
        return this.userProfile;
    }

    public void setUserProfile(UserProfile userProfile) {
        this.userProfile = userProfile;
    }

    public BigDecimal getAmmount() {
        return this.ammount;
    }

    public void setAmmount(BigDecimal ammount) {
        this.ammount = ammount;
    }

    public Date getSubmitDate() {
        return this.submitDate;
    }

    public void setSubmitDate(Date submitDate) {
        this.submitDate = submitDate;
    }

    public Date getSettlementDate() {
        return this.settlementDate;
    }

    public void setSettlementDate(Date settlementDate) {
        this.settlementDate = settlementDate;
    }

    public Byte getCompleted() {
        return this.completed;
    }

    public void setCompleted(Byte completed) {
        this.completed = completed;
    }

    public String getType() {
        return type;
    }

    public void setType(String type) {
        this.type = type;
    }

}
