package com.devlost.jinvest.model;
// Generated 18/10/2017 19:15:54 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;

/**
 * UsersFunds generated by hbm2java
 */
public class UsersFunds  implements java.io.Serializable {


     private Long id;
     private Fund fund;
     private UserProfile userProfile;
     private BigDecimal ammount;
     private BigDecimal profit;
     private Date settlementDate;

    public UsersFunds() {
    }

	
    public UsersFunds(Fund fund, UserProfile userProfile) {
        this.fund = fund;
        this.userProfile = userProfile;
    }
    public UsersFunds(Fund fund, UserProfile userProfile, BigDecimal ammount, Date settlementDate) {
       this.fund = fund;
       this.userProfile = userProfile;
       this.ammount = ammount;
       this.settlementDate = settlementDate;
    }
   
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }
    public Fund getFund() {
        return this.fund;
    }
    
    public void setFund(Fund fund) {
        this.fund = fund;
    }
    public UserProfile getUserProfile() {
        return this.userProfile;
    }
    
    public void setUserProfile(UserProfile userProfile) {
        this.userProfile = userProfile;
    }
    public BigDecimal getAmmount() {
        return this.ammount;
    }
    
    public void setAmmount(BigDecimal ammount) {
        this.ammount = ammount;
    }
    public Date getSettlementDate() {
        return this.settlementDate;
    }
    
    public void setSettlementDate(Date settlementDate) {
        this.settlementDate = settlementDate;
    }

    public BigDecimal getProfit() {
        return profit;
    }

    public void setProfit(BigDecimal profit) {
        this.profit = profit;
    }




}


