package com.devlost.jinvest.model;
// Generated 18/10/2017 19:15:54 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * UserProfile generated by hbm2java
 */
public class UserProfile  implements java.io.Serializable {


     private long userId;
     private Users users;
     private String name;
     private BigDecimal avaliableCash;
     private BigDecimal investedCash;
     private Date birthdate;
     private Set<Transaction> transactions = new HashSet<Transaction>(0);
     private Set<UsersFunds> usersFundses = new HashSet<UsersFunds>(0);

    public UserProfile() {
    }

	
    public UserProfile(long userId, Users users, String name) {
        this.userId = userId;
        this.users = users;
        this.name = name;
    }
    public UserProfile(long userId, Users users, String name, BigDecimal avaliableCash, BigDecimal investedCash, Date birthdate, Set<Transaction> transactions, Set<UsersFunds> usersFundses) {
       this.userId = userId;
       this.users = users;
       this.name = name;
       this.avaliableCash = avaliableCash;
       this.investedCash = investedCash;
       this.birthdate = birthdate;
       this.transactions = transactions;
       this.usersFundses = usersFundses;
    }
   
    public long getUserId() {
        return this.userId;
    }
    
    public void setUserId(long userId) {
        this.userId = userId;
    }
    public Users getUsers() {
        return this.users;
    }
    
    public void setUsers(Users users) {
        this.users = users;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public BigDecimal getAvaliableCash() {
        return this.avaliableCash;
    }
    
    public void setAvaliableCash(BigDecimal avaliableCash) {
        this.avaliableCash = avaliableCash;
    }
    public BigDecimal getInvestedCash() {
        return this.investedCash;
    }
    
    public void setInvestedCash(BigDecimal investedCash) {
        this.investedCash = investedCash;
    }
    public Date getBirthdate() {
        return this.birthdate;
    }
    
    public void setBirthdate(Date birthdate) {
        this.birthdate = birthdate;
    }
    public Set<Transaction> getTransactions() {
        return this.transactions;
    }
    
    public void setTransactions(Set<Transaction> transactions) {
        this.transactions = transactions;
    }
    public Set<UsersFunds> getUsersFundses() {
        return this.usersFundses;
    }
    
    public void setUsersFundses(Set<UsersFunds> usersFundses) {
        this.usersFundses = usersFundses;
    }




}


